<?php
return array (
  'ZC_CLOSE_WHOLE_SITE' => false,
  'ZC_DATABASE_TYPE' => 'mysqli',
  'ZC_SQLITE_NAME' => '',
  'ZC_SQLITE_PRE' => 'zbp_',
  'ZC_MYSQL_SERVER' => 'localhost',
  'ZC_MYSQL_USERNAME' => 'com_com',
  'ZC_MYSQL_PASSWORD' => '8kSjC7zM7P',
  'ZC_MYSQL_NAME' => 'com_com',
  'ZC_MYSQL_CHARSET' => 'utf8mb4',
  'ZC_MYSQL_PRE' => 'zbp_',
  'ZC_MYSQL_ENGINE' => 'InnoDB',
  'ZC_MYSQL_PORT' => '3306',
  'ZC_MYSQL_PERSISTENT' => false,
  'ZC_PGSQL_SERVER' => 'localhost',
  'ZC_PGSQL_USERNAME' => 'postgres',
  'ZC_PGSQL_PASSWORD' => '',
  'ZC_PGSQL_NAME' => '',
  'ZC_PGSQL_CHARSET' => 'utf8',
  'ZC_PGSQL_PRE' => 'zbp_',
  'ZC_PGSQL_PORT' => '5432',
  'ZC_PGSQL_PERSISTENT' => false,
);